name: vps

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: run vps
        run: curl -sSf https://sshx.io/get | sh -s run

      # Sleep for 5.5 hours before restarting (19800 seconds)
      - name: Sleep for 5.5 hours
        run: sleep 19800

      # Trigger the workflow again using GitHub API
      - name: Restart workflow using Account B
        env:
          GH_PAT_B: ${{ secrets.GH_PAT_B }}
        run: |
          curl -X POST \
            -H "Authorization: token $GH_PAT_B" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/main.yml/dispatches \
            -d '{"ref":"main"}'
